### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#153]
We need to clean up `root`, `/resources` and `/terms` and decide what to do with each individual file:

root:

* [x] change_policy.html → remove
* [x] index.html → remove
* [x] references.html → remove

terms:

* [x] decisions.html → keep as md file (?), but unclear if part of standard or not: see #164
* [x] dwc_attributes.rdf → remove, but `status` needs to be defined somewhere: see #165
* [x] dwc_normative.rdf → remove
* [x] history.html → remove
* [x] mapping_abcd.html → remove
* [x] mappings.html → remove
* [x] old_versions.html → remove
* [x] terms.md → move to dwc-qa

resources:

* [x] DarwinCore definition Chinese version.xlsx → remove
* [x] DwCTermsForTranslations_2011-10-16_Japanese15.xlsx → remove
* [x] DwCTermsForTranslations_2011-10-16_Spanish.xls → remove
* [x] dwc_terms.csv → remove, to be replaced by new dwc_terms.csv: see #166
* [x] index.html → remove
* [x] simple_dwc.properties → remove
* [x] simple_dwc_MSAccess.mdb → remove
* [x] simple_dwc_MySQL.sql → remove
* [x] simple_dwc_pgsql.sql → remove
* [x] simple_dwc_terms_header.csv -> dist/simple_dwc_horizontal.csv eafc308
* [x] simple_dwc_terms_list.csv -> dist/simple_dwc_vertical.csv eafc308

**Comment by peterdesmet** [comment]
@tucotuco can you indicate in my issue what should happen with each file? The checkbox should only be checked once the file has been removed/moved.
